name: lint-test

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.6
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: pnpm install && pnpm playwright install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm test:playwright
      - run: pnpm build
